FROM node:20-bookworm-slim

RUN apt-get update && \
    apt-get install -y openssl ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENV NODE_ENV=production

WORKDIR /app

COPY backend/package*.json ./

RUN npm ci

COPY backend/ ./

RUN npx prisma generate

EXPOSE 5000

CMD ["npm", "start"]
