name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo bash -c '
              cd /opt/DevopsdemoApp
              git pull origin main
              docker compose down
              docker builder prune -f
              docker volume prune -a -f
              docker image prune -a -f
              docker system prune -a -f
              docker compose up --build -d 
              docker compose exec backend npx prisma db push
            '
